spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

logging:
  level:
    com:
      example:
        bankcards: DEBUG
    org:
      hibernate:
        transaction: DEBUG
      springframework:
        transaction: DEBUG

jwt:
  cookie:
    refresh:
      name: jwt-refresh-cookie
  expiration:
    accessInMs: 3600000
    refreshInMs: 604800000
  secret:
    access: ${JWT_ACCESS_SECRET}
    refresh: ${JWT_REFRESH_SECRET}