spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

server:
  port: 8080

logging:
  level:
    com:
      example:
        bankcards: DEBUG
    org:
      hibernate:
        transaction: DEBUG
      springframework:
        transaction: DEBUG

token:
  signing:
    key: ${JWT_SECRET_KEY}